spring:
  application:
     name: api-gateway-service 

zuul:
  routes:
    news:
      path: /news/**
      serviceId: NEWS-SERVICE
      stripPrefix: false

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://159.89.36.53:1111/eureka/


server:
  port: 8080
