server:
  port: 1111

# Configuración del Discovery Server
# Como no es un cliente no se registra en Eureka
eureka:
  instance:
    hostname: 159.89.36.53
  client:
    registerWithEureka: false
    fetchRegistry: false