# Spring properties
spring:
  application:
     name: news-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://159.89.36.53:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  
redis:
    host: localhost
    port: 6379
     